### ISSUE TITLE
Refresh the wallpaper

### ISSUE THREAD

**Issue by castrojo** [ublue-os/ubuntu#15]
The wallpaper is a nice throwback, however we need something more modern, here's a NASA image from bing image of the day that we could use .. maybe if we make a darkened version it'll be a nice change?

@aaronlake can you PTAL?

![20230128-BlueBahamas_EN-US2634514272_UHD](https://user-images.githubusercontent.com/1264109/215931168-09a65e24-db28-4919-9f0e-fa89c66abba1.jpg)

**Comment by castrojo** [comment]
https://www.nasa.gov/multimedia/guidelines/index.html

We should be good!

**Comment by aaronlake** [comment]
![desktop-preview](https://user-images.githubusercontent.com/294627/216749516-536b7ff9-7cb1-4acf-9be5-f6e38e6bd613.png)
